# Generated by Django 4.2.4 on 2025-10-08 00:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0008_prfl_endereco_complemento_prfl_endereco_numero_and_more'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(blank=True, max_length=225, null=True)),
                ('CEP', models.CharField(default='', max_length=9, null=True)),
                ('Endereco', models.CharField(default='', max_length=200, null=True)),
                ('Numero', models.CharField(default='0', max_length=10)),
                ('Bairro', models.CharField(blank=True, default='', max_length=125, null=True)),
                ('urlGgleMaps', models.URLField(blank=True, max_length=2000, null=True)),
                ('Cidade', models.CharField(blank=True, max_length=175, null=True)),
                ('Country', models.CharField(default='Brasil', max_length=100)),
                ('IP', models.CharField(max_length=15)),
                ('Perfil_User', models.CharField(blank=True, max_length=125, null=True)),
                ('Atividade', models.TextField(blank=True, null=True)),
                ('DtHr_Atividade', models.DateTimeField(default=datetime.datetime.now)),
                ('UF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.ufestados')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
