# Generated by Django 4.2.4 on 2025-10-08 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_security_logs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Security_Atvdds',
        ),
    ]
